// <auto-generated />
namespace PetGrooming.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class petextensionfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(petextensionfield));
        
        string IMigrationMetadata.Id
        {
            get { return "202002122131261_pet-extension-field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
